lista = ["manzana", "banana","pera"]
print(lista)
print(type(lista))
print(lista[0])
lista.sort()
print(lista)
lista.pop()
print(lista)
lista.append("naranja")
print(lista)
lista.reverse()
print(lista)